### ISSUE TITLE
can not open network file anynet_file

### ISSUE THREAD

**Issue by deep301** [booksim/booksim2#11]
Hi,

I am trying to create a new topology using anynet but it is giving me the following error when i am trying to simulate it using ./boolsim /examples/anynet.anynet_config.

I tried to run it using the example lines given in the readme file also but still the error remains same. Please tel me how to resolve it.

Pakhi

**Comment by fmalazemi** [comment]
By default the topology anynet_file must be in the same folder as booksim.  Or you can define the path specifically in the config file.

**Comment by razzfazz** [comment]
Doesn't look like there's an actual issue here; closing.
