### ISSUE TITLE
Working Routing Functions

### ISSUE THREAD

**Issue by ben-marshall** [booksim/booksim2#13]
I'm using booksim2 and my own analysis code for a research project, and given the responses in issue #7, I wanted to ask which routing _functions_ (as opposed to the actual routers) are known to be correctly implemented?

That is not to say I think they are broken! Just that potentially the code has been neglected, as with the Chaos router, and that this might cause odd results.

I am specifically interested in those functions applicable to two dimensional mesh networks. The two main ones I have been using are `dim_order` and `min_adapt`.

Thanks! :)

**Comment by razzfazz** [comment]
I believe these should be ok, but at the end of the day the best way to really establish that is to just study the code and run some tests yourself.
