### ISSUE TITLE
Running source code of Booksim2 in visual studio 2013

### ISSUE THREAD

**Issue by Afiruzan** [booksim/booksim2#16]
Hi,
How can we run Booksim2 in Visual studio 2013?
When I add src folder to visual studio 2013, I faced with compile error.

Thanks

**Comment by razzfazz** [comment]
Sorry, you'll have to figure out how to import BookSim into Visual Studio yourself. The code itself should be reasonably platform-agnostic, but obviously there are no project files etc. for VS included in the source.

**Comment by Myungwooshik** [comment]
Hi, I have a question about Booksim2.0.
Is there a way to determine source node and destination node?
For example, starting from (x1,y1) and arriving at (x2,y2).

Thanks
