### ISSUE TITLE
latency measurements 

### ISSUE THREAD

**Issue by qweali** [booksim/booksim2#18]
What's the difference between overall network latency and overall packet latency?
And how measure each of them?

**Comment by razzfazz** [comment]
Network latency measures the time it takes each flit to traverse the network. Packet latency measures the time between a packet being generated and consumed; in particular, that includes queueing delay at the network ingress (i.e., time spent sitting in an injection buffer) and serialization delay (i.e., an n-flit packet takes n cycles to be injected into the network flit-by-flit).

**Comment by razzfazz** [comment]
(Closing as this is not actually an issue. Please don't use the issue tracker for asking random questions.)
