### ISSUE TITLE
_int_map key typo 

### ISSUE THREAD

**Issue by calccrypto** [booksim/booksim2#3]
In [booksim_config.cpp](https://github.com/booksim/booksim2/blob/master/src/booksim_config.cpp#L164), `AddStrField("parm_seed", "");` is spelled wrong. It should be `AddStrField("perm_seed", "")`. Currently, `Configuration::GetStr` errors when trying to use `randperm` in the config file.

To reproduce: Change `traffic = uniform;` in [torus88](https://raw.githubusercontent.com/booksim/booksim2/master/src/examples/torus88) to `traffic = randperm;`

**Comment by razzfazz** [comment]
Can you create a pull request, please?

**Comment by razzfazz** [comment]
Merged from pull request #5.
