### ISSUE TITLE
What's the coordinate in Booksim2?

### ISSUE THREAD

**Issue by victorisildur** [booksim/booksim2#6]
Hi,
I'm working on a broadcast routefunc on booksim2, and I found the coordinate is quite subtle.
The only hint I can get is in the routefunc.cpp's `dor_next_mesh()` method:
It returns `2*dim_left` for right or `2*dim_left` for left.
Well, if my network has 2 dimensions, what's dimension `0`, and `2*0` indicate for what?
Also, how is router's id calculated? Plz give me some hint for 2 dimension network.

**Comment by victorisildur** [comment]
Well, seems no one is here.
I found the there may have no meaning in talking about 2 dimensions. The code assumes there are many dimensions, and routefunc calc the direction on every dimension.

**Comment by razzfazz** [comment]
Sorry, you'll be better off asking questions like this on the mailing list.

**Comment by razzfazz** [comment]
Since there's not actually an issue here, I'll go ahead and close this.
