### ISSUE TITLE
Chaos Router

### ISSUE THREAD

**Issue by fmalazemi** [booksim/booksim2#7]
Are there any bugs when using Chaos router with anynet? 
I noticed, _IsEjectionChan function is not used at all. 

Thanks

**Comment by razzfazz** [comment]
I don't think the ChaosRouter code has been touched much in BookSim 2.0; it wouldn't really surprise me if it didn't work. If you want to use that particular router model, you may be better off using the 1.0 codebase.

**Comment by razzfazz** [comment]
You may also want to just compare the chaos router code between 1.0 and 2.0 and check for any obvious breakage; if you feel like cleaning it up, we'd be more than happy to accept pull requests. :)

**Comment by razzfazz** [comment]
is there actually an issue here?

**Comment by razzfazz** [comment]
No feedback -- closing.
